// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputStr struct {
	StudentName string `json:"StudentName"`
	Pass        bool   `json:"Pass"`
}

type SuccessMsg struct {
	OutputStr string `json:"OutputStr"`
}
